### ISSUE TITLE
getMedias for android

### ISSUE THREAD

**Issue by likerRr** [dragermrb/capacitor-plugin-media#4]
Hi, thanks for your work. Just curious why `getMedias` implemented only for ios?

**Comment by dragermrb** [comment]
Hi @likerRr 

This plugin started as a fork of https://github.com/capacitor-community/media with some functionality we needed.

Since the initial plugin did not implement `getMedias` and we did not need it, we have not implemented it.

You need it? May I ask the use case?

**Comment by likerRr** [comment]
Hi, @dragermrb . I wanted to build a simple gallery view app. That's why I needed all the albums names and the way to pull in their content. As far as I understand you implemented such ability for iOS in method `getMedias` by album identifier. But I needed it for Android. Anyway I already solved the issue, so it's up to you rather implement it or not
