### ISSUE TITLE
request: update to v5

### ISSUE THREAD

**Issue by AndreyYolkin** [dragermrb/capacitor-plugin-media#5]
Two hours ago Ionic released Cap 5.0.0 ([Link]( https://github.com/ionic-team/capacitor/releases/tag/5.0.0))

Also they have [migration guide](https://capacitorjs.com/docs/next/updating/plugins/5-0#using-capacitorplugin-migration-v4-to-v5)

Your plugin is very useful and I wonder If you can release v5-compatible version soon?

Have a nice day!

**Comment by dragermrb** [comment]
Published as pre-release

`npm i @whiteguru/capacitor-plugin-media@5.0.1-0`

Can you try it?

**Comment by AndreyYolkin** [comment]
It's working, I succesfully saved the image in album. Thx a lot!
