### ISSUE TITLE
Requests that the specified assets be deleted from PhotoLibrary

### ISSUE THREAD

**Issue by angelofan** [dragermrb/capacitor-plugin-media#6]
This plugin does not have a method for removing assets from the photo library.

I haven't found any capacitor plug-ins that can do this.

https://developer.apple.com/documentation/photokit/phassetchangerequest/1624062-deleteassets

**Comment by angelofan** [comment]
![ea47e8fd39414d07373f8f28acfd728](https://github.com/dragermrb/capacitor-plugin-media/assets/20255750/869e7963-6ce6-40e9-9f5c-f49d246d6f58)

**Comment by dragermrb** [comment]
Hi @angelofan 

We do not have plans in the short term to implement this functionality.

We have to study how to implement it in both iOS and Android.

We will keep this issue open while we study it.

**Comment by dragermrb** [comment]
ping

**Comment by angelofan** [comment]
ping

**Comment by angelofan** [comment]
ping
